---
- name: Clear gathered facts from all
  meta: clear_facts

- name: Dis IPv6 sysctl
  sysctl: name={{ item }} value=1 state=present reload=yes
  with_items:
      - net.ipv4.ip_forward
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6

- name: Disable IPv6 in grub
  replace:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
    replace: 'GRUB_CMDLINE_LINUX="\1 ipv6.disable=1"'
    mode: '0644'
    backup: yes
  notify:
    - grub2-mkconfig
    - reboot_hosts